# Generated by Django 3.1 on 2020-08-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='File'),
        ),
        migrations.AddField(
            model_name='messages',
            name='sender_id',
            field=models.CharField(blank=True, max_length=224, null=True),
        ),
    ]
