# Generated by Django 3.1 on 2020-08-14 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20200814_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='profile_pic',
            new_name='shared_files',
        ),
    ]
