# Generated by Django 3.1 on 2020-08-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20200814_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testdates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_now', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
